container:
  cpu: 2
  memory: 8G
  greedy: true
timeout_in: 120m
env:
  DEBIAN_FRONTEND: "noninteractive"
  CTEST_OUTPUT_ON_FAILURE: "ON"
task:
  container:
    image: ubuntu:devel
    cpu: 4
    memory: 16G
    greedy: true
  env:
    MAKEJOBS: "-j6"  # Reduce jobs to avoid OOM under gcc
  info_script:
    - free -m -h
    - nproc
    - uname --kernel-name --kernel-release
    - lscpu
    - df -h
  install_script:
    - apt update && apt install -y git && apt install -y git ccache build-essential cmake pkg-config python3-zmq libevent-dev libboost-dev qt6-tools-dev qt6-l10n-tools qt6-base-dev systemtap-sdt-dev libqrencode-dev libzmq3-dev libsqlite3-dev libcapnp-dev capnproto ca-certificates
  upstream_clone_script:
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - cd bitcoin-core
  matrix:
    - name: "ubuntu:devel [system libs, asan, clang, libc++, no-qt]"
      install_matrix_script:
        - apt install -y libc++abi-dev libc++-dev clang llvm
        - cd bitcoin-core
        - cmake -B ./bld -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON -DWERROR=ON -DBUILD_GUI=OFF -DWITH_USDT=ON -DWITH_CCACHE=ON -DSANITIZERS=address,integer,undefined -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++;-stdlib=libc++"
    - name: "ubuntu:devel [system libs, asan, clang]"
      install_matrix_script:
        - apt install -y clang llvm
        - cd bitcoin-core
        - cmake -B ./bld -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON -DWERROR=ON -DBUILD_GUI=ON -DWITH_USDT=ON -DWITH_CCACHE=ON -DSANITIZERS=address,integer,undefined -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++"
    - name: "ubuntu:devel [system libs, asan, gcc]"
      install_matrix_script:
        - cd bitcoin-core
        - echo 'nonnull-attribute:streams.h'   >> test/sanitizer_suppressions/ubsan  # runtime error: null pointer passed as argument 1, which is declared to never be null, fwrite
        - echo 'nonnull-attribute:streams.cpp' >> test/sanitizer_suppressions/ubsan  # runtime error: null pointer passed as argument 1, which is declared to never be null, fwrite
        - cmake -B ./bld -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON -DWERROR=OFF -DBUILD_GUI=ON -DWITH_USDT=ON -DWITH_CCACHE=ON -DSANITIZERS=address,undefined -DAPPEND_CXXFLAGS="-Wno-error=maybe-uninitialized"
    - name: "ubuntu:devel [system libs, tsan, clang, libc++, no-qt]"
      install_matrix_script:
        - apt install -y libc++abi-dev libc++-dev clang llvm
        - cd bitcoin-core
        - cmake -B ./bld -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON -DWERROR=ON -DBUILD_GUI=OFF -DWITH_USDT=ON -DWITH_CCACHE=ON -DSANITIZERS=thread -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++;-stdlib=libc++"
    - name: "ubuntu:devel [system libs, tsan, clang]"
      install_matrix_script:
        - apt install -y clang llvm
        - cd bitcoin-core
        - cmake -B ./bld -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON -DWERROR=ON -DBUILD_GUI=ON -DWITH_USDT=ON -DWITH_CCACHE=ON -DSANITIZERS=thread -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++"
    - name: "ubuntu:devel [system libs, tsan, gcc, libqt suppression]"
      install_matrix_script:
        - cd bitcoin-core
        - echo 'race:libQt6Core' >> test/sanitizer_suppressions/tsan
        - echo 'race:libQt6Test' >> test/sanitizer_suppressions/tsan
        - cmake -B ./bld -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON -DWERROR=OFF -DBUILD_GUI=ON -DWITH_USDT=ON -DWITH_CCACHE=ON -DSANITIZERS=thread -DAPPEND_CXXFLAGS="-Wno-error=maybe-uninitialized"
  make_script:
    - cd bitcoin-core
    - cmake --build ./bld $MAKEJOBS
  check_script:
    - cd bitcoin-core
    - export ASAN_OPTIONS="alloc_dealloc_mismatch=0"
    - export LSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/lsan"
    - export TSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/tsan:halt_on_error=1"
    - export UBSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1"
    - ctest --test-dir ./bld ${MAKEJOBS}
    - ./bld/test/functional/test_runner.py $MAKEJOBS --ci --exclude feature_dbcrash --extended --combinedlogslen=199999000 --quiet --failfast --timeout-factor=9
